language: ruby
sudo: false
rvm:
  - 2.5.3

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

env:
  - RAILS_MASTER_KEY=b8cc3ac9ab8a3280b03af3d29b2e50ca

before_install:
  - gem update --system
  - gem install bundler
  - nvm install 11
  - node -v
  - npm i -g yarn@^1.12.1
  - yarn
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver

before_script:
  - psql -c 'create database "uk-police-data_test";' -U postgres
